KAFKA_BOOTSTRAP = "kafka:9092"
TOPIC_PG = "pg_syncai.public.products"
TOPIC_MONGO = "mongo_syncai.syncai_db.items"
QDRANT_HOST = "qdrant"
QDRANT_PORT = 6333
COLLECTION_NAME = "syncai_collection"
VECTOR_SIZE = 768
BATCH_SIZE = 16
OLLAMA_URL = "http://host.docker.internal:11434/api/embeddings"  # host.docker.internal pour Docker sur Windows
